# 作用和 Application 类、 properties 文件相同，保留一个即可。
spring:
  cloud:
    gateway:
      routes:
        - id: GateWayYML
          uri: http://httpbin.org
          predicates:
            - Path=/get
      discovery:
        locator:
          # 开启代理
          enabled: true

  application:
    name: gateway
server:
  port: 1180
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug