# 作用和 Application 类、 properties 文件相同，保留一个即可。
spring:
  cloud:
    gateway:
      routes:
        - id: GateWayYML
          uri: http://httpbin.org
          predicates:
            - Path=/get
            # 某个时间点之后再可以转发
            - After=2020-07-09T21:25:00+08:00[Asia/Shanghai]
            #- Before=2020-07-09T21:25:00+08:00[Asia/Shanghai]
            #- Between=2020-07-09T21:25:00+08:00[Asia/Shanghai],2020-07-09T21:25:00+08:00[Asia/Shanghai]
            # 限定特定请求方法
            - Method=GET
            # 请求必须有 name 参数才会转发
            - Query=name,gw.*
      discovery:
        locator:
          # 开启代理
          enabled: true

  application:
    name: gateway
server:
  port: 1180
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug